[package]
name = "closet"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.73"
axum = "0.6.18"
serde = { version = "1.0", features=["derive"]}
serde_urlencoded = "0.7.1"
shuttle-axum = "0.24.0"
shuttle-runtime = "0.24.0"
silkenweb = "0.5.0"
tokio = "1.28.2"
